#!/usr/bin/env python3
"""Write unofficial tech interview/hackathon MCQ papers into public/tests/."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "public" / "tests"


def q(qid: str, prompt: str, options: list[str], correct: int, explanation: str) -> dict:
    return {
        "id": qid,
        "prompt": prompt,
        "options": options,
        "correctIndex": correct,
        "explanation": explanation,
    }


def paper(pid: str, title: str, minutes: int, questions: list[dict]) -> dict:
    return {
        "id": pid,
        "title": title,
        "durationMinutes": minutes,
        "questions": questions,
    }


LOGICAL = paper(
    "hackathon-logical",
    "Hackathon Screen \u2014 Logical Reasoning",
    25,
    [
        q("q1", "Find the next number: 2, 6, 12, 20, 30, ?", ["36", "40", "42", "48"], 2,
          "The terms are n(n+1): 1×2, 2×3, 3×4, 4×5, 5×6, so next is 6×7 = 42."),
        q("q2", "Odd one out: HTTP, FTP, SMTP, HTML", ["HTTP", "FTP", "SMTP", "HTML"], 3,
          "HTTP, FTP, and SMTP are network protocols. HTML is a markup language."),
        q("q3", "If TEAM is written as VGCO (each letter shifted +2), how is CODE written?",
          ["EQEG", "EQFG", "DPFF", "FQFG"], 1,
          "C→E, O→Q, D→F, E→G, so CODE → EQFG."),
        q("q4", "A is B's sister. C is B's mother. D is C's father. How is D related to A?",
          ["Uncle", "Brother", "Maternal grandfather", "Father"], 2,
          "C is A's mother, so C's father D is A's maternal grandfather."),
        q("q5", "What is the angle between the hour and minute hands at 3:00?",
          ["0°", "75°", "90°", "180°"], 2,
          "At 3:00 the hands sit on 3 and 12, which are a right angle."),
        q("q6", "If today is Wednesday, what day of the week is it 61 days from now?",
          ["Sunday", "Monday", "Tuesday", "Thursday"], 1,
          "61 = 8×7 + 5, so add 5 weekdays to Wednesday: Monday."),
        q("q7", "A team of 40 people: 25 know Python, 20 know Java, and 10 know both. How many know neither?",
          ["5", "10", "15", "20"], 0,
          "25 + 20 − 10 = 35 know at least one language. 40 − 35 = 5 know neither."),
        q("q8", "A 3×3×3 cube is painted on all outer faces, then cut into 27 unit cubes. How many unit cubes have paint on exactly two faces?",
          ["6", "8", "12", "24"], 2,
          "Each of the 12 edges contributes one edge-center cube with two painted faces (corners have three)."),
        q("q9", "Find the next group: ACE, BDF, CEG, ?", ["DFH", "DEH", "DFI", "CFH"], 0,
          "Each letter advances by 1 from the previous group: D, F, H."),
        q("q10", "In a queue of 20 people, A is 7th from the left. How many people are behind A?",
          ["7", "12", "13", "14"], 2,
          "20 − 7 = 13 people behind A."),
        q("q11", "You walk 5 km north, 5 km east, then 5 km south. How far are you from the start?",
          ["0 km", "5 km", "10 km", "15 km"], 1,
          "North and south cancel, leaving 5 km east of the start."),
        q("q12", "All roses are flowers. Some flowers fade quickly. Which conclusion must follow?",
          ["Some roses fade quickly", "All flowers are roses", "No rose fades quickly", "None of these must follow"], 3,
          "The roses may all lie in the part of 'flowers' that do not fade quickly."),
        q("q13", "8 workers finish a job in 10 days at a constant rate. How many days do 4 workers need for the same job?",
          ["5", "10", "16", "20"], 3,
          "Work is 80 worker-days. 4 workers need 80/4 = 20 days."),
        q("q14", "What is the angle between the hour and minute hands at 3:15?",
          ["0°", "7.5°", "15°", "30°"], 1,
          "Minute hand at 90°. Hour hand at 3×30 + 15×0.5 = 97.5°. Difference 7.5°."),
        q("q15", "If the day before yesterday was Thursday, what day is tomorrow?",
          ["Sunday", "Monday", "Friday", "Saturday"], 0,
          "Day before yesterday = Thursday ⇒ today = Saturday ⇒ tomorrow = Sunday."),
        q("q16", "Find the next number: 3, 8, 15, 24, 35, ?", ["46", "47", "48", "49"], 2,
          "These are n² − 1 for n = 2,3,4,5,6, so next is 7² − 1 = 48."),
        q("q17", "A is taller than B. B is taller than C. Who is the shortest?",
          ["A", "B", "C", "Cannot be determined"], 2,
          "A > B > C, so C is shortest."),
        q("q18", "All APIs are endpoints. Some endpoints are cached. Therefore some APIs are cached. The inference is:",
          ["Always true", "Always false", "Does not necessarily follow", "True only if no cache exists"], 2,
          "The cached endpoints might be ones that are not APIs."),
        q("q19", "A number is coded by the count of letters in its English name: 1→3 (ONE), 2→3 (TWO), 4→4 (FOUR). What is 11 coded as?",
          ["5", "6", "7", "8"], 1,
          "ELEVEN has 6 letters."),
        q("q20", "From a point you go 5 km north, 3 km east, 2 km south, then 3 km west. Distance from the start?",
          ["0 km", "3 km", "5 km", "8 km"], 1,
          "Net movement is 3 km north and 0 km east, so 3 km from the start."),
    ],
)

QUANT = paper(
    "hackathon-quant",
    "Hackathon Screen \u2014 Quantitative Aptitude",
    25,
    [
        q("q1", "What is 15% of 240?", ["24", "30", "36", "40"], 2, "0.15 × 240 = 36."),
        q("q2", "If x + y = 10 and xy = 21, what is x² + y²?", ["58", "79", "100", "121"], 0,
          "x² + y² = (x + y)² − 2xy = 100 − 42 = 58."),
        q("q3", "A car covers 60 km in 45 minutes. What is its speed in km/h?", ["45", "60", "75", "80"], 3,
          "45 minutes = 0.75 h. 60 / 0.75 = 80 km/h."),
        q("q4", "A can finish a job in 10 days and B in 15 days. Working together, how many days do they need?",
          ["5", "6", "8", "12"], 1,
          "1/10 + 1/15 = 1/6, so 6 days."),
        q("q5", "Two fair dice are rolled. Probability that the sum is 7?",
          ["1/12", "1/8", "1/6", "1/4"], 2,
          "Six outcomes (1,6)…(6,1) out of 36, so 6/36 = 1/6."),
        q("q6", "In how many distinct ways can 5 people stand in a line?",
          ["25", "60", "120", "125"], 2, "5! = 120."),
        q("q7", "What is log₂(8)?", ["2", "3", "4", "8"], 1, "2³ = 8."),
        q("q8", "A score rises from 50 to 75. What is the percent increase?",
          ["25%", "33%", "50%", "150%"], 2,
          "(75 − 50)/50 = 50%."),
        q("q9", "GCD of 48 and 18?", ["4", "6", "8", "9"], 1, "48 = 2×18 + 12, 18 = 1×12 + 6, 12 = 2×6."),
        q("q10", "LCM of 4, 6, and 8?", ["12", "24", "36", "48"], 1, "2³ × 3 = 24."),
        q("q11", "12² − 8² = ?", ["16", "40", "80", "208"], 2,
          "Difference of squares: (12 − 8)(12 + 8) = 4 × 20 = 80."),
        q("q12", "The binary number 1101 is what in decimal?", ["11", "12", "13", "14"], 2,
          "8 + 4 + 0 + 1 = 13."),
        q("q13", "What is 2¹⁰ modulo 3?", ["0", "1", "2", "1024"], 1,
          "2 ≡ −1 (mod 3), so 2¹⁰ ≡ (−1)¹⁰ ≡ 1. Also 1024 = 341×3 + 1."),
        q("q14", "An item costs 250. Sold at 20% profit, the selling price is?",
          ["270", "280", "300", "320"], 2, "1.2 × 250 = 300."),
        q("q15", "Two numbers are in ratio 3:5. If the first is 24, the second is?",
          ["30", "36", "40", "48"], 2, "24/3 × 5 = 40."),
        q("q16", "Average of 10, 20, 30, 40, 50?", ["25", "30", "35", "40"], 1, "150 / 5 = 30."),
        q("q17", "Compound interest on 1000 at 10% per year for 2 years (annual compounding) is?",
          ["200", "210", "220", "1210"], 1,
          "Amount = 1000 × 1.1² = 1210. Interest = 210."),
        q("q18", "0.25 as a percentage is?", ["0.25%", "2.5%", "25%", "250%"], 2, "0.25 = 25/100 = 25%."),
        q("q19", "3/4 + 1/6 = ?", ["2/5", "4/10", "5/12", "11/12"], 3,
          "9/12 + 2/12 = 11/12."),
        q("q20", "If 30% of x is 90, then x is?", ["120", "180", "270", "300"], 3,
          "0.3x = 90 ⇒ x = 300."),
    ],
)

CS = paper(
    "hackathon-cs",
    "Tech Interview \u2014 Computer Science Fundamentals",
    30,
    [
        q("q1", "Worst-case time complexity of binary search on a sorted array of n items?",
          ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 1,
          "Each step halves the search space."),
        q("q2", "A stack is:",
          ["FIFO", "LIFO", "Random access only", "Priority-ordered"], 1,
          "Last in, first out."),
        q("q3", "Average-case time for lookup in a well-dimensioned hash table?",
          ["O(1)", "O(log n)", "O(n)", "O(n²)"], 0,
          "Expected constant time with a good hash and load factor."),
        q("q4", "A queue is:",
          ["LIFO", "FIFO", "Sorted always", "A binary tree"], 1,
          "First in, first out."),
        q("q5", "Which protocol provides reliable, ordered byte streams?",
          ["UDP", "IP", "TCP", "ICMP"], 2,
          "TCP is connection-oriented and reliable. UDP is not."),
        q("q6", "HTTP status 404 means:",
          ["Unauthorized", "Forbidden", "Not Found", "Server error"], 2,
          "404 is Not Found."),
        q("q7", "Random access to index i in a dynamic array vs a singly linked list is typically:",
          ["O(1) vs O(n)", "O(n) vs O(1)", "O(1) vs O(1)", "O(log n) vs O(log n)"], 0,
          "Arrays index in constant time; lists must walk i nodes."),
        q("q8", "A recursive function's pending calls are stored on the:",
          ["Heap only", "Call stack", "Instruction cache only", "GPU"], 1,
          "Each nested call pushes a stack frame."),
        q("q9", "for i in 1..n: for j in 1..n: work()  has complexity:",
          ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], 2,
          "n × n constant-time iterations."),
        q("q10", "BFS on a graph typically uses a:",
          ["Stack", "Queue", "Max-heap only", "Union-find only"], 1,
          "A queue expands nodes in level order."),
        q("q11", "DFS is naturally implemented with a:",
          ["Queue", "Stack (or the call stack)", "Bloom filter", "Priority queue only"], 1,
          "Depth-first search is stack-based."),
        q("q12", "Threads of one process typically share:",
          ["Nothing", "The same address space", "Separate kernels", "Separate PIDs always"], 1,
          "Threads share the process memory; processes do not."),
        q("q13", "HTTPS encrypts HTTP using:",
          ["FTP", "TLS", "SSH only", "SMTP"], 1,
          "HTTPS is HTTP over TLS."),
        q("q14", "DNS primarily maps:",
          ["MAC to IP", "Domain names to IP addresses", "Ports to processes", "Users to passwords"], 1,
          "Name resolution."),
        q("q15", "The safest common way to avoid SQL injection is:",
          ["String-concatenating queries", "Parameterized queries / bound parameters", "Disabling indexes", "Using GET only"], 1,
          "Keep user data out of the SQL parse tree."),
        q("q16", "In Git, a commit records:",
          ["Only a diff with no parent", "A snapshot plus metadata and parent(s)", "The working tree only", "Remote config only"], 1,
          "Commits point at a tree and parent commits."),
        q("q17", "A well-behaved HTTP GET is expected to be:",
          ["Unsafe and non-idempotent", "Safe and idempotent", "Always stateful", "A write method"], 1,
          "GET should not change server state and repeating it should not change the result."),
        q("q18", "In ACID, the 'A' stands for:",
          ["Availability", "Atomicity", "Authentication", "Aggregation"], 1,
          "Transactions are all-or-nothing."),
        q("q19", "Circular wait is a necessary condition for:",
          ["Paging", "Deadlock", "DNS lookup", "Hashing"], 1,
          "One of Coffman's deadlock conditions."),
        q("q20", "In IEEE-754 floating point, 0.1 + 0.2 == 0.3 is:",
          ["Always true", "Often false because of binary rounding", "A compiler bug only", "Undefined in every language"], 1,
          "Those decimals are not exact binary fractions."),
        q("q21", "Garbage collection's job is to:",
          ["Compile source", "Reclaim memory that is no longer reachable", "Schedule CPU cores", "Encrypt disks"], 1,
          "It frees unused heap objects."),
        q("q22", "CORS is enforced by:",
          ["The database", "The browser, using response headers from the server", "DNSSEC only", "The OS kernel always"], 1,
          "Browsers block cross-origin reads unless the server opts in."),
        q("q23", "A perfect binary tree with 3 levels (root is level 1) has how many nodes?",
          ["3", "4", "6", "7"], 3,
          "1 + 2 + 4 = 7."),
        q("q24", "In languages with wrapping unsigned integers, 255 + 1 in 8-bit unsigned is typically:",
          ["256", "0", "255", "Error always"], 1,
          "It wraps modulo 256."),
        q("q25", "CAP theorem says that in a partition, a distributed store cannot simultaneously guarantee:",
          ["Cache and compression", "Consistency and availability", "CPU and RAM", "IPv4 and IPv6"], 1,
          "You pick C or A when P happens."),
    ],
)

PUZZLES = paper(
    "hackathon-puzzles",
    "Tech Interview \u2014 Problem Solving Puzzles",
    20,
    [
        q("q1", "Monty Hall: three doors, one car. You pick one. Host opens a goat door. Switching wins with probability:",
          ["1/3", "1/2", "2/3", "1"], 2,
          "Your first pick is right 1/3 of the time; the other unopened door then holds the car 2/3 of the time."),
        q("q2", "About how many people do you need so that P(shared birthday) is about 50% (365 days, ignore leap years)?",
          ["12", "23", "183", "365"], 1,
          "The birthday paradox: 23 people is about 50%."),
        q("q3", "1000 bottles, one poisoned. A test strip shows a result after a delay and can be reused only as a bit in one round. Minimum testers for one round of tests?",
          ["8", "9", "10", "1000"], 2,
          "2¹⁰ = 1024 ≥ 1000, so 10 binary tests."),
        q("q4", "Why are manhole covers typically round?",
          ["They are cheaper to paint", "A round cover cannot fall through its opening", "Only circles fit city blocks", "They weigh less than any other shape"], 1,
          "The circle's width is constant; a square cover can be tilted through the diagonal."),
        q("q5", "Two ropes each burn in 60 minutes, unevenly. You can light ends. How can you measure 45 minutes?",
          ["Impossible", "Light both ends of both ropes", "Light both ends of rope A and one end of B; when A dies, light B's other end", "Cut both ropes in half"], 2,
          "A finishes at 30 minutes. Lighting B's other end then burns the remaining 30-minute length in 15 minutes. Total 45."),
        q("q6", "With jugs of 3 L and 5 L, can you measure exactly 4 L?",
          ["No", "Yes", "Only with a 4 L jug", "Only using a scale"], 1,
          "Classic water-jug problem; 4 is a multiple of gcd(3,5)=1 and ≤ 5."),
        q("q7", "Farmer, fox, chicken, grain: boat holds farmer plus one. First trip should take:",
          ["The fox", "The chicken", "The grain", "Nothing"], 1,
          "Otherwise fox eats chicken or chicken eats grain."),
        q("q8", "Hilbert's hotel is full. To free room 1 for one new guest, move occupant of room n to:",
          ["Room 1", "Room n−1", "Room n+1", "Room 2n only"], 2,
          "Everyone shifts up one room; infinitely many rooms remain."),
        q("q9", "12 balls, one different weight (heavier or lighter). A balance scale. Minimum weighings in the worst case?",
          ["2", "3", "4", "12"], 1,
          "Each weighing has 3 outcomes; 3³ = 27 > 24 possibilities."),
        q("q10", "How many times do the hour and minute hands overlap in 12 hours?",
          ["10", "11", "12", "13"], 1,
          "They overlap 11 times every 12 hours (they almost-meet around 11 and 12 as one event)."),
        q("q11", "100 closed doors, 100 people. Person k toggles multiples of k. How many doors are open at the end?",
          ["1", "10", "50", "100"], 1,
          "Door n is toggled d(n) times and ends open iff n is a square. There are 10 squares ≤ 100."),
        q("q12", "2 eggs, 100 floors, minimize worst-case drops. The optimal worst-case count is:",
          ["10", "14", "50", "100"], 1,
          "Need k+(k−1)+…+1 ≥ 100 ⇒ k(k+1)/2 ≥ 100 ⇒ k = 14."),
        q("q13", "5 rational pirates, 100 indivisible coins. Most senior proposes a take-it-or-leave-it split; ties reject. How many coins does the most senior keep in the standard solution?",
          ["0", "20", "98", "100"], 2,
          "A offers 98 to self, 0, 1, 0, 1 so two others still prefer A over the next game."),
        q("q14", "A plane mirror appears to reverse left and right, not up and down, because it actually reverses:",
          ["Gravity", "The front–back axis", "Color", "Time"], 1,
          "The mirror maps each point to the point opposite along the normal."),
        q("q15", "3 switches, 3 bulbs in another room. You may enter the bulb room once. A working strategy uses heat. After waiting, a bulb that is off but warm means:",
          ["Its switch was never on", "Its switch was on earlier then turned off", "It is broken", "All switches control it"], 1,
          "On for a while then off: warm and dark. Currently on: lit. Never on: cold and dark."),
    ],
)

ALGOS = paper(
    "hackathon-algorithms",
    "Tech Interview \u2014 Algorithms and Complexity",
    25,
    [
        q("q1", "Mergesort comparison complexity in the worst case is:",
          ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], 1,
          "Divide and merge: always Θ(n log n) comparisons."),
        q("q2", "Quicksort worst-case time (bad pivots) is:",
          ["O(n log n)", "O(n²)", "O(n)", "O(log n)"], 1,
          "Highly unbalanced partitions give quadratic time."),
        q("q3", "Building a binary heap from n items with Floyd's method is:",
          ["Θ(n)", "Θ(n log n) only", "Θ(n²)", "Θ(1)"], 0,
          "Heapify runs in linear time."),
        q("q4", "Dijkstra's algorithm as commonly taught assumes:",
          ["Negative cycles are required", "No negative edge weights", "The graph is a tree", "Vertices have degree 2"], 1,
          "Negative edges can break the greedy distance finalization."),
        q("q5", "A topological order exists for a directed graph if and only if it is a:",
          ["Complete graph", "DAG", "Bipartite graph", "Connected undirected graph"], 1,
          "Directed acyclic graph."),
        q("q6", "Which sort is stable?",
          ["Heapsort", "Standard in-place quicksort", "Mergesort", "Selection sort"], 2,
          "Mergesort can preserve equal-key order; classic heapsort and in-place quicksort do not."),
        q("q7", "A hash collision means:",
          ["The table is empty", "Two keys map to the same bucket", "The computer crashed", "n = 1"], 1,
          "Different keys, same hash index."),
        q("q8", "A common O(1) LRU cache uses:",
          ["Only an array", "Hash map + doubly linked list", "Only a BST", "Only a stack"], 1,
          "Map for lookup, list for recency order."),
        q("q9", "A trie is especially good for:",
          ["Prefix queries on strings", "Sorting integers in O(1)", "Replacing all hash tables", "Matrix multiply"], 0,
          "Shared prefixes walk a path from the root."),
        q("q10", "Checking whether a string is a palindrome in linear time is often done with:",
          ["Dijkstra", "Two pointers from both ends", "Bellman-Ford", "Prim"], 1,
          "Compare s[i] and s[n-1-i]."),
        q("q11", "Finding the longest substring with at most k distinct characters is a classic:",
          ["NP-complete packing", "Sliding-window problem", "Min-cut problem", "FFT problem"], 1,
          "Expand/shrink a window while maintaining counts."),
        q("q12", "Kadane's algorithm finds:",
          ["Shortest path", "Maximum subarray sum", "MST", "Bipartite matching"], 1,
          "Linear scan tracking the best ending here."),
        q("q13", "Binary search requires the sequence to be:",
          ["A linked list", "Sorted (under the search order)", "Random", "A graph"], 1,
          "The decision 'go left or right' needs order."),
        q("q14", "BFS from s on an unweighted graph yields:",
          ["Longest path", "Shortest path in number of edges", "Minimum spanning tree", "A topological order always"], 1,
          "Level equals distance in edges."),
        q("q15", "Detecting a cycle in a directed graph can be done with:",
          ["DFS colors / recursion stack", "Binary search", "Kadane", "Two-sum only"], 0,
          "A back edge to an ancestor on the DFS stack means a cycle."),
        q("q16", "Union-find with path compression and union-by-rank is effectively:",
          ["O(n) per op", "Almost O(1) amortized (inverse Ackermann)", "O(n²)", "O(2ⁿ)"], 1,
          "α(n) grows extremely slowly."),
        q("q17", "A Bloom filter may report:",
          ["False positives, not false negatives (for membership as designed)", "False negatives only", "Neither", "Sorted order"], 0,
          "Bits can collide (false yes); a 'no' is certain if no bits were set."),
        q("q18", "Space for the call stack of a straightforward factorial(n) recursion is:",
          ["O(1)", "O(log n)", "O(n)", "O(n!)"], 2,
          "n stacked frames."),
        q("q19", "Appending to a geometric-resizing array is:",
          ["O(n) worst every time", "O(1) amortized", "O(n²) amortized", "O(log n) amortized always for each char"], 1,
          "Occasional copies are paid across many cheap appends."),
        q("q20", "Any comparison-based sorting algorithm needs",
          ["O(n) comparisons in the worst case always", "Ω(n log n) comparisons in the worst case", "O(1) comparisons", "No lower bound"], 1,
          "There are n! orders; a binary decision tree has height Ω(log n!)."),
    ],
)

PRACTICAL = paper(
    "hackathon-practical",
    "Hackathon Practical \u2014 Web, Security, and Systems",
    25,
    [
        q("q1", "Storing a session JWT in localStorage is mainly risky because of:",
          ["CSS", "XSS stealing the token", "Slow DNS", "Missing alt text"], 1,
          "Any script on the page can read localStorage."),
        q("q2", "To prevent SQL injection, prefer:",
          ["Building SQL with string + user input", "Parameterized queries", "Disabling HTTPS", "Client-side only checks"], 1,
          "Bind values separately from the query string."),
        q("q3", "A browser CORS error on a fetch usually means:",
          ["The JSON is invalid", "The server did not allow that origin/method/header", "TCP is disabled", "The disk is full"], 1,
          "The browser enforces the server's Access-Control-* headers."),
        q("q4", "HTTP 429 typically means:",
          ["OK", "Redirect", "Too Many Requests (rate limited)", "Teapot only"], 2,
          "The client hit a rate limit."),
        q("q5", "Which method is expected to be idempotent?",
          ["POST", "PUT", "PATCH always", "CONNECT"], 1,
          "Repeating PUT with the same body should leave the same resource state."),
        q("q6", "Compared with short polling, WebSockets are better when you need:",
          ["A single static file", "Low-latency bidirectional updates", "Only SEO HTML", "DNSSEC"], 1,
          "A persistent channel, not repeated empty HTTP polls."),
        q("q7", "API keys and database passwords should live in:",
          ["Git history on purpose", "Environment / a secret manager, not the repo", "Frontend bundle comments", "Public Gists"], 1,
          "Keep secrets off source control."),
        q("q8", "An HTTPS page loading a script over HTTP is:",
          ["Fine always", "Mixed content and usually blocked", "Faster", "Required for CORS"], 1,
          "Browsers block active mixed content."),
        q("q9", "Cursor-based pagination compared with large OFFSET is often:",
          ["Slower on big skips", "More stable as rows are inserted", "Impossible in SQL", "Only for graphs"], 1,
          "OFFSET skips cost grows; a cursor key seeks."),
        q("q10", "A container compared with a full VM typically:",
          ["Emulates a whole hardware BIOS always", "Shares the host kernel and is lighter", "Cannot run Linux", "Replaces TCP"], 1,
          "Containers isolate processes, not a full guest OS."),
        q("q11", "The primary defense against stored XSS in HTML is:",
          ["Bigger fonts", "Context-aware escaping / sanitizing output", "Using tables", "HTTP 204"], 1,
          "Do not treat untrusted data as HTML/JS."),
        q("q12", "A common CSRF defense for cookie-authenticated POST forms is:",
          ["No Content-Type", "Anti-CSRF token or SameSite cookies", "Disabling JavaScript forever", "Using GET for deletes"], 1,
          "The attacker site must not be able to forge the user's cookie-backed request."),
        q("q13", "HTTP 401 vs 403:",
          ["401 not authenticated; 403 authenticated but not allowed", "They are identical", "403 means not found", "401 means rate limit"], 0,
          "401: who are you? 403: I know you, no access."),
        q("q14", "A lockfile (package-lock.json / similar) is committed so that:",
          ["npm becomes faster forever", "Installs reproduce the same dependency versions", "Tests never fail", "Git can skip node_modules diffs"], 1,
          "It pins the resolved tree."),
        q("q15", "In a hackathon CI setup, the most valuable default is:",
          ["Deploy broken main", "Run tests (and lint) on every pull request", "Skip reviews", "Commit secrets to pass CI"], 1,
          "Catch failures before merge."),
        q("q16", "Cache-Control: no-store on an HTML response tells caches to:",
          ["Store forever", "Not store the response", "Gzip twice", "Use IPv6"], 1,
          "Sensitive pages should not be cached."),
        q("q17", "Optimistic UI means:",
          ["Assume the write succeeded and update the UI, reconcile if it fails", "Never call the server", "Block the UI until timeout", "Use only GET"], 0,
          "Snappy UI with a rollback path."),
        q("q18", "localStorage vs IndexedDB: IndexedDB is the better default when you need:",
          ["A few flags only", "Larger structured data and indexes", "CSS variables", "TLS certificates"], 1,
          "localStorage is a small synchronous string map."),
        q("q19", "The N+1 query problem is:",
          ["One query too few", "Fetching a list then querying once per item", "Using too many indexes", "A DNS loop"], 1,
          "Fix with a join, IN-list, or dataloader batch."),
        q("q20", "Feature flags are used to:",
          ["Replace version control", "Turn features on/off without a full redeploy", "Encrypt disks", "Name CSS classes"], 1,
          "Decouple release from deploy."),
    ],
)

TEMPLATE = {
    "id": "my-paper-id",
    "title": "Paper title",
    "durationMinutes": 20,
    "questions": [
        {
            "id": "q1",
            "prompt": "Question text",
            "options": ["Option A", "Option B", "Option C", "Option D"],
            "correctIndex": 0,
            "explanation": "Why A is correct.",
        }
    ],
}

PAPERS = [LOGICAL, QUANT, CS, PUZZLES, ALGOS, PRACTICAL]


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    index = {
        "tests": [
            {
                "id": p["id"],
                "title": p["title"],
                "durationMinutes": p["durationMinutes"],
                "questionCount": len(p["questions"]),
                "file": f"{p['id']}.json",
            }
            for p in PAPERS
        ]
    }
    (ROOT / "index.json").write_text(json.dumps(index, indent=2) + "\n")
    (ROOT / "_template.json").write_text(json.dumps(TEMPLATE, indent=2) + "\n")
    for p in PAPERS:
        (ROOT / f"{p['id']}.json").write_text(json.dumps(p, indent=2) + "\n")
        print(f"{p['id']}: {len(p['questions'])} questions")


if __name__ == "__main__":
    main()
